// The Polyglot Vocab note type, for setting up a fresh Anki profile. Copied
// from the original collection's note type (without its Balinese fields and
// card templates), so new users get the same cards: one card per language
// direction, audio inline, and Notes under a "more" disclosure.

export const vocabNoteFields = ["English", "Indonesian", "Thai", "Japanese", "Audio_English", "Audio_Indonesian", "Audio_Thai", "Audio_Japanese", "Notes_English", "Notes_Indonesian", "Notes_Thai", "Notes_Japanese", "Origin"];

export const vocabNoteCss = ".card {\n  font-family: -apple-system, \"Segoe UI\", \"Noto Sans Thai\", \"Noto Sans JP\", \"Noto Sans\", sans-serif;\n  font-size: 28px;\n  text-align: center;\n  color: #1a1a1a;\n  background-color: #fafafa;\n  padding: 24px 20px;\n}\n\n.tag {\n  font-size: 13px;\n  letter-spacing: 0.08em;\n  text-transform: uppercase;\n  color: #8a8a8a;\n  margin-bottom: 8px;\n}\n\n.prompt {\n  font-size: 34px;\n  line-height: 1.3;\n}\n\nhr#answer {\n  margin: 22px auto;\n  width: 60%;\n  border: none;\n  border-top: 1px solid #ddd;\n}\n\n.answer {\n  font-size: 34px;\n  line-height: 1.3;\n  color: #0e6b56;\n  margin-bottom: 10px;\n}\n\ndetails.more {\n  margin: 18px auto 0;\n  text-align: left;\n  display: inline-block;\n  max-width: 480px;\n  font-size: 16px;\n  line-height: 1.5;\n  color: #3a3a3a;\n}\n\ndetails.more summary {\n  cursor: pointer;\n  text-align: center;\n  color: #8a8a8a;\n  font-size: 13px;\n  letter-spacing: 0.04em;\n}\n\ndetails.more[open] summary {\n  margin-bottom: 10px;\n}\n\n.origin {\n  margin-top: 16px;\n  display: inline-block;\n  font-size: 11px;\n  letter-spacing: 0.03em;\n  padding: 3px 10px;\n  border-radius: 20px;\n  background: #eeeeee;\n  color: #999999;\n}\n\ndetails.more .origin {\n  margin-top: 0;\n  margin-bottom: 10px;\n}";

export const vocabCardTemplates: { Name: string; Front: string; Back: string }[] = [
  { Name: "English → Indonesian", Front: "{{#English}}{{#Indonesian}}\n<div class=\"tag\">ENGLISH</div>\n<div class=\"prompt\">{{English}}</div>\n{{#Audio_English}}{{Audio_English}}{{/Audio_English}}\n{{/Indonesian}}{{/English}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">INDONESIAN</div>\n<div class=\"answer\">{{Indonesian}}</div>\n{{#Audio_Indonesian}}{{Audio_Indonesian}}{{/Audio_Indonesian}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more</summary>\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_Indonesian}}{{Notes_Indonesian}}{{/Notes_Indonesian}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_Indonesian}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Indonesian}}\n</details>\n{{/Notes_Indonesian}}\n{{/Origin}}" },
  { Name: "English → Thai", Front: "{{#English}}{{#Thai}}\n<div class=\"tag\">ENGLISH</div>\n<div class=\"prompt\">{{English}}</div>\n{{#Audio_English}}{{Audio_English}}{{/Audio_English}}\n{{/Thai}}{{/English}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">THAI</div>\n<div class=\"answer\">{{Thai}}</div>\n{{#Audio_Thai}}{{Audio_Thai}}{{/Audio_Thai}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more</summary>\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_Thai}}{{Notes_Thai}}{{/Notes_Thai}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_Thai}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Thai}}\n</details>\n{{/Notes_Thai}}\n{{/Origin}}" },
  { Name: "English → Japanese", Front: "{{#English}}{{#Japanese}}\n<div class=\"tag\">ENGLISH</div>\n<div class=\"prompt\">{{English}}</div>\n{{#Audio_English}}{{Audio_English}}{{/Audio_English}}\n{{/Japanese}}{{/English}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">JAPANESE</div>\n<div class=\"answer\">{{Japanese}}</div>\n{{#Audio_Japanese}}{{Audio_Japanese}}{{/Audio_Japanese}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more</summary>\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_Japanese}}{{Notes_Japanese}}{{/Notes_Japanese}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_Japanese}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Japanese}}\n</details>\n{{/Notes_Japanese}}\n{{/Origin}}" },
  { Name: "Indonesian → English", Front: "{{#Indonesian}}{{#English}}\n<div class=\"tag\">INDONESIAN</div>\n<div class=\"prompt\">{{Indonesian}}</div>\n{{#Audio_Indonesian}}{{Audio_Indonesian}}{{/Audio_Indonesian}}\n{{/English}}{{/Indonesian}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">ENGLISH</div>\n<div class=\"answer\">{{English}}</div>\n{{#Audio_English}}{{Audio_English}}{{/Audio_English}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more</summary>\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_English}}{{Notes_English}}{{/Notes_English}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_English}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_English}}\n</details>\n{{/Notes_English}}\n{{/Origin}}" },
  { Name: "Thai → English", Front: "{{#Thai}}{{#English}}\n<div class=\"tag\">THAI</div>\n<div class=\"prompt\">{{Thai}}</div>\n{{#Audio_Thai}}{{Audio_Thai}}{{/Audio_Thai}}\n{{#Notes_Thai}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Thai}}\n</details>\n{{/Notes_Thai}}\n{{/English}}{{/Thai}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">ENGLISH</div>\n<div class=\"answer\">{{English}}</div>\n{{#Audio_English}}{{Audio_English}}{{/Audio_English}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more</summary>\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_English}}{{Notes_English}}{{/Notes_English}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_English}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_English}}\n</details>\n{{/Notes_English}}\n{{/Origin}}" },
  { Name: "Japanese → English", Front: "{{#Japanese}}{{#English}}\n<div class=\"tag\">JAPANESE</div>\n<div class=\"prompt\">{{Japanese}}</div>\n{{#Audio_Japanese}}{{Audio_Japanese}}{{/Audio_Japanese}}\n{{#Notes_Japanese}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Japanese}}\n</details>\n{{/Notes_Japanese}}\n{{/English}}{{/Japanese}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">ENGLISH</div>\n<div class=\"answer\">{{English}}</div>\n{{#Audio_English}}{{Audio_English}}{{/Audio_English}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more</summary>\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_English}}{{Notes_English}}{{/Notes_English}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_English}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_English}}\n</details>\n{{/Notes_English}}\n{{/Origin}}" },
  { Name: "Indonesian → Thai", Front: "{{#Indonesian}}{{#Thai}}\n<div class=\"tag\">INDONESIAN</div>\n<div class=\"prompt\">{{Indonesian}}</div>\n{{#Audio_Indonesian}}{{Audio_Indonesian}}{{/Audio_Indonesian}}\n{{/Thai}}{{/Indonesian}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">THAI</div>\n<div class=\"answer\">{{Thai}}</div>\n{{#Audio_Thai}}{{Audio_Thai}}{{/Audio_Thai}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more</summary>\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_Thai}}{{Notes_Thai}}{{/Notes_Thai}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_Thai}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Thai}}\n</details>\n{{/Notes_Thai}}\n{{/Origin}}" },
  { Name: "Indonesian → Japanese", Front: "{{#Indonesian}}{{#Japanese}}\n<div class=\"tag\">INDONESIAN</div>\n<div class=\"prompt\">{{Indonesian}}</div>\n{{#Audio_Indonesian}}{{Audio_Indonesian}}{{/Audio_Indonesian}}\n{{/Japanese}}{{/Indonesian}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">JAPANESE</div>\n<div class=\"answer\">{{Japanese}}</div>\n{{#Audio_Japanese}}{{Audio_Japanese}}{{/Audio_Japanese}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more</summary>\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_Japanese}}{{Notes_Japanese}}{{/Notes_Japanese}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_Japanese}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Japanese}}\n</details>\n{{/Notes_Japanese}}\n{{/Origin}}" },
  { Name: "Thai → Indonesian", Front: "{{#Thai}}{{#Indonesian}}\n<div class=\"tag\">THAI</div>\n<div class=\"prompt\">{{Thai}}</div>\n{{#Audio_Thai}}{{Audio_Thai}}{{/Audio_Thai}}\n{{/Indonesian}}{{/Thai}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">INDONESIAN</div>\n<div class=\"answer\">{{Indonesian}}</div>\n{{#Audio_Indonesian}}{{Audio_Indonesian}}{{/Audio_Indonesian}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_Indonesian}}{{Notes_Indonesian}}{{/Notes_Indonesian}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_Indonesian}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Indonesian}}\n</details>\n{{/Notes_Indonesian}}\n{{/Origin}}" },
  { Name: "Thai → Japanese", Front: "{{#Thai}}{{#Japanese}}\n<div class=\"tag\">THAI</div>\n<div class=\"prompt\">{{Thai}}</div>\n{{#Audio_Thai}}{{Audio_Thai}}{{/Audio_Thai}}\n{{/Japanese}}{{/Thai}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">JAPANESE</div>\n<div class=\"answer\">{{Japanese}}</div>\n{{#Audio_Japanese}}{{Audio_Japanese}}{{/Audio_Japanese}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more</summary>\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_Japanese}}{{Notes_Japanese}}{{/Notes_Japanese}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_Japanese}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Japanese}}\n</details>\n{{/Notes_Japanese}}\n{{/Origin}}" },
  { Name: "Japanese → Indonesian", Front: "{{#Japanese}}{{#Indonesian}}\n<div class=\"tag\">JAPANESE</div>\n<div class=\"prompt\">{{Japanese}}</div>\n{{#Audio_Japanese}}{{Audio_Japanese}}{{/Audio_Japanese}}\n{{/Indonesian}}{{/Japanese}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">INDONESIAN</div>\n<div class=\"answer\">{{Indonesian}}</div>\n{{#Audio_Indonesian}}{{Audio_Indonesian}}{{/Audio_Indonesian}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_Indonesian}}{{Notes_Indonesian}}{{/Notes_Indonesian}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_Indonesian}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Indonesian}}\n</details>\n{{/Notes_Indonesian}}\n{{/Origin}}" },
  { Name: "Japanese → Thai", Front: "{{#Japanese}}{{#Thai}}\n<div class=\"tag\">JAPANESE</div>\n<div class=\"prompt\">{{Japanese}}</div>\n{{#Audio_Japanese}}{{Audio_Japanese}}{{/Audio_Japanese}}\n{{/Thai}}{{/Japanese}}", Back: "{{FrontSide}}\n<hr id=\"answer\">\n<div class=\"tag\">THAI</div>\n<div class=\"answer\">{{Thai}}</div>\n{{#Audio_Thai}}{{Audio_Thai}}{{/Audio_Thai}}\n{{#Origin}}\n<details class=\"more\">\n<summary>more\n<div class=\"origin\">origin: {{Origin}}</div>\n{{#Notes_Thai}}{{Notes_Thai}}{{/Notes_Thai}}\n</details>\n{{/Origin}}\n{{^Origin}}\n{{#Notes_Thai}}\n<details class=\"more\">\n<summary>more</summary>\n{{Notes_Thai}}\n</details>\n{{/Notes_Thai}}\n{{/Origin}}" },
];
